server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: aigou-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jinchuan1997/aigou-config.git
          username: jinhcuan1997
          password: Li1242810771